name: clang-format check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  formatting-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: jidicula/clang-format-action@v2.0.0
