name: Valgrind tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  valgrind-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: |
        sudo apt-get update
        sudo apt-get install check valgrind
    - run: pip install meson ninja
    - run: meson build --buildtype=debugoptimized
      env:
        CC: gcc
    - run: ninja -C build -v
    - run: |
        cd build
        CK_FORK=no meson test \
          --print-errorlogs \
          --wrapper="valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all --error-exitcode=97"
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: testlog-valgrind
        path: build/meson-logs/testlog-valgrind.txt

